name: Build and Deploy Monorepo

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    env:
      NEXT_PUBLIC_API_URL: ${{ github.ref == 'refs/heads/master' && vars.PROD_BACKEND_API_URL || vars.DEV_BACKEND_API_URL }}
      HEROKU_APP_NAME: ${{ github.ref == 'refs/heads/master' && secrets.HEROKU_PROD_APP_NAME || secrets.HEROKU_DEV_APP_NAME }}
      FIREBASE_TARGET: ${{ github.ref == 'refs/heads/master' && 'aiguana-log' || 'aiguana-log-dev' }}
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${{ github.ref == 'refs/heads/master' && secrets.HEROKU_PROD_APP_NAME || secrets.HEROKU_DEV_APP_NAME }}/web

    steps:
      # Step 1: Check out the repository code under $GITHUB_WORKSPACE
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      # Step 3: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build All Packages
        run: pnpm build

      - name: Verify API Build Output
        run: ls -R apps/api/dist

      - name: Verify Web Build Output
        run: ls -R apps/web/dist

      - name: Verify Shared Types Build Output
        run: ls -R apps/shared-types/dist

      - name: Install Heroku CLI
        run: npm install -g heroku

      - name: Log in to Heroku Container Registry
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build Docker image
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        run: docker build -t $HEROKU_REGISTRY_IMAGE -f apps/api/Dockerfile ./apps/api

      - name: Push Docker image to Heroku
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        run: docker push $HEROKU_REGISTRY_IMAGE

      - name: Release Docker image on Heroku
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app $HEROKU_APP_NAME

        # Step: Deploy Frontend Artifacts to Firebase
      - name: Deploy Frontend to Firebase
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          projectId: aiguana-log
          target: ${{ env.FIREBASE_TARGET }}
