name: Build and Deploy Monorepo

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    env:
      NEXT_PUBLIC_API_URL: ${{ github.ref == 'refs/heads/master' && vars.PROD_BACKEND_API_URL || vars.DEV_BACKEND_API_URL }}
      HEROKU_APP_NAME: ${{ github.ref == 'refs/heads/master' && secrets.HEROKU_PROD_APP_NAME || secrets.HEROKU_DEV_APP_NAME }}
      FIREBASE_TARGET: ${{ github.ref == 'refs/heads/master' && 'aiguana-log' || 'aiguana-log-dev' }}

    steps:
      # Step 1: Check out the repository code under $GITHUB_WORKSPACE
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      # Step 3: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build All Packages
        run: pnpm build
        # TODO: Ensure the root 'pnpm build' command correctly builds shared-types, api, and web
      - name: Deploy API to Heroku
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Deploying API to Heroku app: $HEROKU_APP_NAME"
          # Use git to deploy only the necessary files from the api package
          # This includes compiled code (dist), package files, and runtime dependencies
          git subtree split --prefix=apps/api -b heroku-api-deploy
          cd apps/api # Navigate into the api dir to potentially prune devDependencies

          # Create a temporary package.json with only production dependencies
          # (Requires jq tool - might need 'apt-get update && apt-get install -y jq')
          # Or use a more robust method like npm/pnpm prune if needed
          # For simplicity now, we deploy node_modules generated by root install,
          # assuming Heroku buildpack handles pruning or uses package.json correctly.
          # A more optimized approach would prepare a clean deployment package.

          cd ../.. # Go back to root to push the subtree

          # Force push the subtree branch containing only api files to Heroku main
          # Heroku will then use package.json and the start script with node_modules
          git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git `git subtree split --prefix=apps/api HEAD`:refs/heads/main --force

          # Note: This still relies on Heroku installing production dependencies
          # based on the apps/api/package.json pushed. It avoids the tsc build on Heroku.

      # Step: Deploy Frontend Artifacts to Firebase
      - name: Deploy Frontend to Firebase
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          projectId: aiguana-log
          target: ${{ env.FIREBASE_TARGET }}
