name: Build and Deploy Monorepo

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    env:
      NEXT_PUBLIC_API_URL: ${{ github.ref == 'refs/heads/master' && vars.PROD_BACKEND_API_URL || vars.DEV_BACKEND_API_URL }}

    steps:
      # Step 1: Check out the repository code under $GITHUB_WORKSPACE
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      # Step 3: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build All Packages
        run: pnpm build
        # TODO: Ensure the root 'pnpm build' command correctly builds shared-types, api, and web

      - name: Deploy API to Heroku Dev
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_DEV_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "apps/api"

      - name: Deploy Frontend to Firebase Dev
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          projectId: aiguana-log
          target: aiguana-log-dev

      - name: Deploy API to Heroku Prod
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_PROD_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "apps/api"

      - name: Deploy Frontend to Firebase Prod
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          projectId: aiguana-log
          target: aiguana-log
